function value = GetGaussianCartesianMatrix(obj, ...
    atomTypeA, valenceOrbitalA, gaussianExponentA, xyzA,...
    atomTypeB, valenceOrbitalB, gaussianExponentB, xyzB,...
    rAB, overlapSASB, axis)
gauPlusAB = gaussianExponentA+gaussianExponentB;
gauMultAB = gaussianExponentA*gaussianExponentB;
dxyz = xyzA - xyzB;
% valenceOrbitalA = double(valenceOrbitalA);
% valenceOrbitalB = double(valenceOrbitalB);
if(valenceOrbitalA == 1 && valenceOrbitalB == 1)
    value = gaussianExponentA*xyzA(axis) + gaussianExponentB*xyzB(axis);
    value = value ./ gauPlusAB;
    value = value .* overlapSASB;
elseif( (valenceOrbitalA == 1 && axis == 1 && valenceOrbitalB == 4) || ...
        (valenceOrbitalA == 1 && axis == 1 && valenceOrbitalB == 2) || ...
        (valenceOrbitalA == 1 && axis == 1 && valenceOrbitalB == 3) || ...
        (valenceOrbitalA == 1 && axis == 1 && valenceOrbitalB == 5) || ...
        (valenceOrbitalA == 1 && axis == 1 && valenceOrbitalB == 6) || ...
        (valenceOrbitalA == 1 && axis == 1 && valenceOrbitalB == 8) ||...
        (valenceOrbitalA == 1 && axis == 1 && valenceOrbitalB == 9) || ...
        (valenceOrbitalA == 1 && axis == 1 && valenceOrbitalB == 7) || ...
        (valenceOrbitalA == 1 && axis == 2 && valenceOrbitalB == 4) || ...
        (valenceOrbitalA == 1 && axis == 2 && valenceOrbitalB == 2) || ...
        (valenceOrbitalA == 1 && axis == 2 && valenceOrbitalB == 3) ||...
        (valenceOrbitalA == 1 && axis == 2 && valenceOrbitalB == 5) ||...
        (valenceOrbitalA == 1 && axis == 2 && valenceOrbitalB == 6) ||...
        (valenceOrbitalA == 1 && axis == 2 && valenceOrbitalB == 8) ||...
        (valenceOrbitalA == 1 && axis == 2 && valenceOrbitalB == 9) || ...
        (valenceOrbitalA == 1 && axis == 2 && valenceOrbitalB == 7) || ...
        (valenceOrbitalA == 1 && axis == 3 && valenceOrbitalB == 4) || ...
        (valenceOrbitalA == 1 && axis == 3 && valenceOrbitalB == 2) || ...
        (valenceOrbitalA == 1 && axis == 3 && valenceOrbitalB == 3) ||...
        (valenceOrbitalA == 1 && axis == 3 && valenceOrbitalB == 5) ||...
        (valenceOrbitalA == 1 && axis == 3 && valenceOrbitalB == 6) ||...
        (valenceOrbitalA == 1 && axis == 3 && valenceOrbitalB == 8) ||...
        (valenceOrbitalA == 1 && axis == 3 && valenceOrbitalB == 9) ||...
        (valenceOrbitalA == 1 && axis == 3 && valenceOrbitalB == 7) )
    if(axis == 1)
        pOrbital = 4;
    elseif(axis == 2)
        pOrbital = 2;
    elseif(axis == 3)
        pOrbital = 3;
    end
    overlapAOs1 = obj.GetGaussianOverlapAOs(atomTypeA,...
        valenceOrbitalA, ...
        gaussianExponentA, ...
        atomTypeB, ...
        valenceOrbitalB, ...
        gaussianExponentB,...
        dxyz,...
        rAB,...
        overlapSASB);
    overlapAOs2 = obj.GetGaussianOverlapAOs(atomTypeA,...
        pOrbital, ...
        gaussianExponentA, ...
        atomTypeB, ...
        valenceOrbitalB, ...
        gaussianExponentB,...
        dxyz, ...
        rAB,...
        overlapSASB);
    value = overlapAOs2/(2.0*sqrt(gaussianExponentA))+xyzA(axis)*overlapAOs1;
elseif( (valenceOrbitalA == 4    && axis == 1 && valenceOrbitalB == 1) ||...
        (valenceOrbitalA == 2    && axis == 1 && valenceOrbitalB == 1) ||...
        (valenceOrbitalA == 3    && axis == 1 && valenceOrbitalB == 1) ||...
        (valenceOrbitalA == 5   && axis == 1 && valenceOrbitalB == 1) ||...
        (valenceOrbitalA == 6   && axis == 1 && valenceOrbitalB == 1) ||...
        (valenceOrbitalA == 8   && axis == 1 && valenceOrbitalB == 1) ||...
        (valenceOrbitalA == 9 && axis == 1 && valenceOrbitalB == 1) ||...
        (valenceOrbitalA == 7   && axis == 1 && valenceOrbitalB == 1) ||...
        (valenceOrbitalA == 4    && axis == 2 && valenceOrbitalB == 1) ||...
        (valenceOrbitalA == 2    && axis == 2 && valenceOrbitalB == 1) ||...
        (valenceOrbitalA == 3    && axis == 2 && valenceOrbitalB == 1) ||...
        (valenceOrbitalA == 5   && axis == 2 && valenceOrbitalB == 1) ||...
        (valenceOrbitalA == 6   && axis == 2 && valenceOrbitalB == 1) ||...
        (valenceOrbitalA == 8   && axis == 2 && valenceOrbitalB == 1) ||...
        (valenceOrbitalA == 9 && axis == 2 && valenceOrbitalB == 1) ||...
        (valenceOrbitalA == 7   && axis == 2 && valenceOrbitalB == 1) ||...
        (valenceOrbitalA == 4    && axis == 3 && valenceOrbitalB == 1) ||...
        (valenceOrbitalA == 2    && axis == 3 && valenceOrbitalB == 1) ||...
        (valenceOrbitalA == 3    && axis == 3 && valenceOrbitalB == 1) ||...
        (valenceOrbitalA == 5   && axis == 3 && valenceOrbitalB == 1) ||...
        (valenceOrbitalA == 6   && axis == 3 && valenceOrbitalB == 1) ||...
        (valenceOrbitalA == 8   && axis == 3 && valenceOrbitalB == 1) ||...
        (valenceOrbitalA == 9 && axis == 3 && valenceOrbitalB == 1) ||...
        (valenceOrbitalA == 7   && axis == 3 && valenceOrbitalB == 1) )
    if(axis == 1)
        pOrbital = 4;
    elseif(axis == 2)
        pOrbital = 2;
    elseif(axis == 3)
        pOrbital = 3;
    end
    overlapAOs1 = obj.GetGaussianOverlapAOs(atomTypeA,......
        valenceOrbitalA, ......
        gaussianExponentA, ......
        atomTypeB, ......
        valenceOrbitalB, ......
        gaussianExponentB,......
        dxyz, ...
        rAB,...
        overlapSASB);
    overlapAOs2 = obj.GetGaussianOverlapAOs(atomTypeA,......
        valenceOrbitalA, ......
        gaussianExponentA, ......
        atomTypeB, ......
        pOrbital, ...
        gaussianExponentB,......
        dxyz, ...
        rAB,...
        overlapSASB);
    value = overlapAOs2/(2.0*sqrt(gaussianExponentB))+xyzB(axis)*overlapAOs1;
elseif( (valenceOrbitalA == 4 && axis == 1 && valenceOrbitalB == valenceOrbitalA) ||...
        (valenceOrbitalA == 2 && axis == 2 && valenceOrbitalB == valenceOrbitalA) ||...
        (valenceOrbitalA == 3 && axis == 3 && valenceOrbitalB == valenceOrbitalA) )
    temp1 = gaussianExponentA*xyzA(axis) + gaussianExponentB*xyzB(axis);
    temp2 = gaussianExponentA*xyzA(axis) - gaussianExponentA*xyzB(axis);
    temp3 = gaussianExponentB*xyzA(axis) - gaussianExponentB*xyzB(axis);
    value = 0.5*(temp1+temp2-temp3);
    value = value - temp1*temp2*temp3/gauPlusAB;
    value = value .* 4.0*sqrt(gauMultAB)/(gauPlusAB*gauPlusAB);
    value = value .* overlapSASB;
elseif( (valenceOrbitalA == 4 && axis == 2 && valenceOrbitalB == valenceOrbitalA) ||...
        (valenceOrbitalA == 4 && axis == 3 && valenceOrbitalB == valenceOrbitalA) ||...
        (valenceOrbitalA == 2 && axis == 1 && valenceOrbitalB == valenceOrbitalA) ||...
        (valenceOrbitalA == 2 && axis == 3 && valenceOrbitalB == valenceOrbitalA) ||...
        (valenceOrbitalA == 3 && axis == 1 && valenceOrbitalB == valenceOrbitalA) ||...
        (valenceOrbitalA == 3 && axis == 2 && valenceOrbitalB == valenceOrbitalA) )
    if(valenceOrbitalA == 4)
        piDirection = 1;
    elseif(valenceOrbitalA == 2)
        piDirection = 2;
    elseif(valenceOrbitalA == 3)
        piDirection = 3;
    end
    temp1 = gaussianExponentA*xyzA(piDirection) - gaussianExponentA*xyzB(piDirection);
    temp2 = gaussianExponentB*xyzA(piDirection) - gaussianExponentB*xyzB(piDirection);
    value = 0.5 - temp1*temp2/gauPlusAB;
    value = value .* (gaussianExponentA*xyzA(axis) + gaussianExponentB*xyzB(axis));
    value = value .* 4.0*sqrt(gauMultAB)/(gauPlusAB*gauPlusAB);
    value = value .* overlapSASB;
elseif( (valenceOrbitalA == 4 && axis == 2 && valenceOrbitalB == 2) ||...
        (valenceOrbitalA == 4 && axis == 3 && valenceOrbitalB == 3) ||...
        (valenceOrbitalA == 2 && axis == 1 && valenceOrbitalB == 4) ||...
        (valenceOrbitalA == 2 && axis == 3 && valenceOrbitalB == 3) ||...
        (valenceOrbitalA == 3 && axis == 1 && valenceOrbitalB == 4) ||...
        (valenceOrbitalA == 3 && axis == 2 && valenceOrbitalB == 2) )
    if(valenceOrbitalA == 4)
        piDirectionA = 1;
    elseif(valenceOrbitalA == 2)
        piDirectionA = 2;
    elseif(valenceOrbitalA == 3)
        piDirectionA = 3;
    end
    temp1 = gaussianExponentA*xyzA(axis) + gaussianExponentB*xyzB(axis);
    temp2 = gaussianExponentA*xyzA(axis) - gaussianExponentA*xyzB(axis);
    value = 0.5 + temp1*temp2/gauPlusAB;
    value = value .* (gaussianExponentB*xyzA(piDirectionA) - gaussianExponentB*xyzB(piDirectionA));
    value = value .* (-4.0*sqrt(gauMultAB)/(gauPlusAB*gauPlusAB));
    value = value .* overlapSASB;
elseif( (valenceOrbitalA == 2 && axis == 2 && valenceOrbitalB == 4) ||...
        (valenceOrbitalA == 2 && axis == 2 && valenceOrbitalB == 3) ||...
        (valenceOrbitalA == 4 && axis == 1 && valenceOrbitalB == 2) ||...
        (valenceOrbitalA == 4 && axis == 1 && valenceOrbitalB == 3) ||...
        (valenceOrbitalA == 3 && axis == 3 && valenceOrbitalB == 4) ||...
        (valenceOrbitalA == 3 && axis == 3 && valenceOrbitalB == 2) )
    if(valenceOrbitalB == 4)
        piDirectionB = 1;
    elseif(valenceOrbitalB == 2)
        piDirectionB = 2;
    elseif(valenceOrbitalB == 3)
        piDirectionB = 3;
    end
    temp1 = gaussianExponentA*xyzA(axis) + gaussianExponentB*xyzB(axis);
    temp2 = gaussianExponentB*xyzA(axis) - gaussianExponentB*xyzB(axis);
    value = 0.5 - temp1*temp2/gauPlusAB;
    value = value .* (gaussianExponentA*xyzA(piDirectionB) - gaussianExponentA*xyzB(piDirectionB));
    value = value .* 4.0*sqrt(gauMultAB)/(gauPlusAB*gauPlusAB);
    value = value .* overlapSASB;
elseif( (valenceOrbitalA == 4 && axis == 2 && valenceOrbitalB == 3) ||...
        (valenceOrbitalA == 2 && axis == 3 && valenceOrbitalB == 4) ||...
        (valenceOrbitalA == 3 && axis == 1 && valenceOrbitalB == 2) ||...
        (valenceOrbitalA == 4 && axis == 3 && valenceOrbitalB == 2) ||...
        (valenceOrbitalA == 3 && axis == 2 && valenceOrbitalB == 4) ||...
        (valenceOrbitalA == 2 && axis == 1 && valenceOrbitalB == 3) )
    if(valenceOrbitalA == 4)
        piDirectionA = 1;
    elseif(valenceOrbitalA == 2)
        piDirectionA = 2;
    elseif(valenceOrbitalA == 3)
        piDirectionA = 3;
    end
    if(valenceOrbitalB == 4)
        piDirectionB = 1;
    elseif(valenceOrbitalB == 2)
        piDirectionB = 2;
    elseif(valenceOrbitalB == 3)
        piDirectionB = 3;
    end
    temp1 = gaussianExponentB*xyzA(piDirectionA) - gaussianExponentB*xyzB(piDirectionA);
    temp2 = gaussianExponentA*xyzA(axis)         + gaussianExponentB*xyzB(axis);
    temp3 = gaussianExponentA*xyzA(piDirectionB) - gaussianExponentA*xyzB(piDirectionB);
    value = -4.0*sqrt(gauMultAB)/(gauPlusAB*gauPlusAB*gauPlusAB);
    value = value .* temp1*temp2*temp3;
    value = value .* overlapSASB;
elseif( (valenceOrbitalA == 4 && axis == 1 && valenceOrbitalB == 5) ||...
        (valenceOrbitalA == 2 && axis == 2 && valenceOrbitalB == 5) ||...
        (valenceOrbitalA == 2 && axis == 2 && valenceOrbitalB == 6) ||...
        (valenceOrbitalA == 3 && axis == 3 && valenceOrbitalB == 6) ||...
        (valenceOrbitalA == 3 && axis == 3 && valenceOrbitalB == 8) ||...
        (valenceOrbitalA == 4 && axis == 1 && valenceOrbitalB == 8) )
    if(valenceOrbitalB == 5)
        if(axis == 1)
            anotherAxis = 2;
        else
            anotherAxis = 1;
        end
    elseif(valenceOrbitalB == 6)
        if(axis == 2)
            anotherAxis = 3;
            
        else
            anotherAxis = 2;
        end
    elseif(valenceOrbitalB == 8)
        if(axis == 3)
            anotherAxis = 1;
            
        else
            anotherAxis = 3;
        end
    end
    overlapAOs1 = obj.GetGaussianOverlapAOs(atomTypeA,......
        valenceOrbitalA, ......
        gaussianExponentA, ......
        atomTypeB, ......
        valenceOrbitalB, ......
        gaussianExponentB,......
        dxyz, ...
        rAB,...
        overlapSASB);
    value = 0.5*gaussianExponentA*dxyz(axis)...
        -gaussianExponentB*dxyz(axis)...
        +(gaussianExponentB*gaussianExponentB)*gaussianExponentA...
        *dxyz(axis)*dxyz(axis)*dxyz(axis)/gauPlusAB;
    value = value .* 8.0*gaussianExponentA*sqrt(gaussianExponentA)...
        *gaussianExponentB*dxyz(anotherAxis)*overlapSASB/(gauPlusAB*gauPlusAB*gauPlusAB);
    value = value + xyzA(axis)*overlapAOs1;
elseif( (valenceOrbitalA == 5 && axis == 1 && valenceOrbitalB == 4) ||...
        (valenceOrbitalA == 5 && axis == 2 && valenceOrbitalB == 2) ||...
        (valenceOrbitalA == 6 && axis == 2 && valenceOrbitalB == 2) ||...
        (valenceOrbitalA == 6 && axis == 3 && valenceOrbitalB == 3) ||...
        (valenceOrbitalA == 8 && axis == 3 && valenceOrbitalB == 3) ||...
        (valenceOrbitalA == 8 && axis == 1 && valenceOrbitalB == 4) )
    if(valenceOrbitalA == 5)
        if(axis == 1)
            anotherAxis = 2;
        else
            anotherAxis = 1;
        end
    elseif(valenceOrbitalA == 6)
        if(axis == 2)
            anotherAxis = 3;
        else
            anotherAxis = 2;
        end
    elseif(valenceOrbitalA == 8)
        if(axis == 3)
            anotherAxis = 1;
        else
            anotherAxis = 3;
        end
    end
    overlapAOs1 = obj.GetGaussianOverlapAOs(atomTypeA,......
        valenceOrbitalA, ......
        gaussianExponentA, ......
        atomTypeB, ......
        valenceOrbitalB, ......
        gaussianExponentB,......
        dxyz,...
        rAB,...
        overlapSASB);
    value = 0.5*gaussianExponentB*dxyz(axis)...
        -gaussianExponentA*dxyz(axis)...
        +(gaussianExponentA*gaussianExponentA)*gaussianExponentB...
        *dxyz(axis)*dxyz(axis)*dxyz(axis)/gauPlusAB;
    value = value .* 8.0*gaussianExponentB*sqrt(gaussianExponentB)*gaussianExponentA...
        *dxyz(anotherAxis)*overlapSASB/(gauPlusAB*gauPlusAB*gauPlusAB);
    value = value + xyzB(axis)*overlapAOs1;
elseif( (valenceOrbitalA == 3 && axis == 3 && valenceOrbitalB == 5) ||...
        (valenceOrbitalA == 4 && axis == 1 && valenceOrbitalB == 6) ||...
        (valenceOrbitalA == 2 && axis == 2 && valenceOrbitalB == 8) )
    if(axis == 1)
        anotherAxis1 = 2;
        anotherAxis2 = 3;
    elseif(axis == 2)
        anotherAxis1 = 1;
        anotherAxis2 = 3;
    elseif(axis == 3)
        anotherAxis1 = 1;
        anotherAxis2 = 2;
    end
    overlapAOs1 = obj.GetGaussianOverlapAOs(atomTypeA,......
        valenceOrbitalA, ......
        gaussianExponentA, ......
        atomTypeB, ......
        valenceOrbitalB, ......
        gaussianExponentB,... ...
        dxyz, ...
        rAB,...
        overlapSASB);
    value = 0.5+gaussianExponentB*gaussianExponentB*dxyz(axis)*dxyz(axis)/gauPlusAB;
    value = value .* 8.0*gaussianExponentA*gaussianExponentA*sqrt(gaussianExponentA)...
        *gaussianExponentB*overlapSASB/(gauPlusAB*gauPlusAB*gauPlusAB);
    value = value .* dxyz(anotherAxis1)*dxyz(anotherAxis2);
    value = value + xyzA(axis)*overlapAOs1;
elseif( (valenceOrbitalA == 5 && axis == 3 && valenceOrbitalB == 3) ||...
        (valenceOrbitalA == 6 && axis == 1 && valenceOrbitalB == 4) ||...
        (valenceOrbitalA == 8 && axis == 2 && valenceOrbitalB == 2) )
    if(axis == 1)
        anotherAxis1 = 2;
        anotherAxis2 = 3;
    elseif(axis == 2)
        anotherAxis1 = 1;
        anotherAxis2 = 3;
    elseif(axis == 3)
        anotherAxis1 = 1;
        anotherAxis2 = 2;
    end
    overlapAOs1 = obj.GetGaussianOverlapAOs(atomTypeA,......
        valenceOrbitalA, ......
        gaussianExponentA, ......
        atomTypeB, ......
        valenceOrbitalB, ......
        gaussianExponentB,... ...
        dxyz, ...
        rAB,...
        overlapSASB);
    value = 0.5+gaussianExponentA*gaussianExponentA*dxyz(axis)*dxyz(axis)/gauPlusAB;
    value = value .* 8.0*gaussianExponentB*gaussianExponentB*sqrt(gaussianExponentB)...
        *gaussianExponentA*overlapSASB/(gauPlusAB*gauPlusAB*gauPlusAB);
    value = value .* dxyz(anotherAxis1)*dxyz(anotherAxis2);
    value = value + xyzB(axis)*overlapAOs1;
elseif( (valenceOrbitalA == 4 && axis == 2 && valenceOrbitalB == 5) ||...
        (valenceOrbitalA == 4 && axis == 3 && valenceOrbitalB == 5) ||...
        (valenceOrbitalA == 2 && axis == 1 && valenceOrbitalB == 5) ||...
        (valenceOrbitalA == 2 && axis == 3 && valenceOrbitalB == 5) ||...
        (valenceOrbitalA == 3 && axis == 1 && valenceOrbitalB == 5) ||...
        (valenceOrbitalA == 3 && axis == 2 && valenceOrbitalB == 5) ||...
        (valenceOrbitalA == 4 && axis == 2 && valenceOrbitalB == 6) ||...
        (valenceOrbitalA == 4 && axis == 3 && valenceOrbitalB == 6) ||...
        (valenceOrbitalA == 2 && axis == 1 && valenceOrbitalB == 6) ||...
        (valenceOrbitalA == 2 && axis == 3 && valenceOrbitalB == 6) ||...
        (valenceOrbitalA == 3 && axis == 1 && valenceOrbitalB == 6) ||...
        (valenceOrbitalA == 3 && axis == 2 && valenceOrbitalB == 6) ||...
        (valenceOrbitalA == 4 && axis == 2 && valenceOrbitalB == 8) ||...
        (valenceOrbitalA == 4 && axis == 3 && valenceOrbitalB == 8) ||...
        (valenceOrbitalA == 2 && axis == 1 && valenceOrbitalB == 8) ||...
        (valenceOrbitalA == 2 && axis == 3 && valenceOrbitalB == 8) ||...
        (valenceOrbitalA == 3 && axis == 1 && valenceOrbitalB == 8) ||...
        (valenceOrbitalA == 3 && axis == 2 && valenceOrbitalB == 8) ||...
        (valenceOrbitalA == 4 && axis == 2 && valenceOrbitalB == 9) ||...
        (valenceOrbitalA == 4 && axis == 3 && valenceOrbitalB == 9) ||...
        (valenceOrbitalA == 2 && axis == 1 && valenceOrbitalB == 9) ||...
        (valenceOrbitalA == 2 && axis == 3 && valenceOrbitalB == 9) ||...
        (valenceOrbitalA == 3 && axis == 1 && valenceOrbitalB == 9) ||...
        (valenceOrbitalA == 3 && axis == 2 && valenceOrbitalB == 9) ||...
        (valenceOrbitalA == 4 && axis == 2 && valenceOrbitalB == 7) ||...
        (valenceOrbitalA == 4 && axis == 3 && valenceOrbitalB == 7) ||...
        (valenceOrbitalA == 2 && axis == 1 && valenceOrbitalB == 7) ||...
        (valenceOrbitalA == 2 && axis == 3 && valenceOrbitalB == 7) ||...
        (valenceOrbitalA == 3 && axis == 1 && valenceOrbitalB == 7) ||...
        (valenceOrbitalA == 3 && axis == 2 && valenceOrbitalB == 7) )
    if( (valenceOrbitalA == 2 && axis == 1) ||...
            (valenceOrbitalA == 4 && axis == 2) )
        dOrbital = 5;
    elseif( (valenceOrbitalA == 2 && axis == 3) ||...
            (valenceOrbitalA == 3 && axis == 2) )
        dOrbital = 6;
    elseif( (valenceOrbitalA == 4 && axis == 3) ||...
            (valenceOrbitalA == 3 && axis == 1) )
        dOrbital = 8;
    end
    overlapAOs1 = obj.GetGaussianOverlapAOs(atomTypeA,......
        valenceOrbitalA, ......
        gaussianExponentA, ......
        atomTypeB, ......
        valenceOrbitalB, ......
        gaussianExponentB,......
        dxyz, ...
        rAB,...
        overlapSASB);
    overlapAOs2 = obj.GetGaussianOverlapAOs(atomTypeA,......
        dOrbital, ...
        gaussianExponentA, ......
        atomTypeB, ......
        valenceOrbitalB, ......
        gaussianExponentB,......
        dxyz, ...
        rAB,...
        overlapSASB);
    value = overlapAOs2/(2.0*sqrt(gaussianExponentA))+xyzA(axis)*overlapAOs1;
    
    
elseif( (valenceOrbitalA == 5   && axis == 2 && valenceOrbitalB == 4) ||...
        (valenceOrbitalA == 5   && axis == 3 && valenceOrbitalB == 4) ||...
        (valenceOrbitalA == 5   && axis == 1 && valenceOrbitalB == 2) ||...
        (valenceOrbitalA == 5   && axis == 3 && valenceOrbitalB == 2) ||...
        (valenceOrbitalA == 5   && axis == 1 && valenceOrbitalB == 3) ||...
        (valenceOrbitalA == 5   && axis == 2 && valenceOrbitalB == 3) ||...
        (valenceOrbitalA == 6   && axis == 2 && valenceOrbitalB == 4) ||...
        (valenceOrbitalA == 6   && axis == 3 && valenceOrbitalB == 4) ||...
        (valenceOrbitalA == 6   && axis == 1 && valenceOrbitalB == 2) ||...
        (valenceOrbitalA == 6   && axis == 3 && valenceOrbitalB == 2) ||...
        (valenceOrbitalA == 6   && axis == 1 && valenceOrbitalB == 3) ||...
        (valenceOrbitalA == 6   && axis == 2 && valenceOrbitalB == 3) ||...
        (valenceOrbitalA == 8   && axis == 2 && valenceOrbitalB == 4) ||...
        (valenceOrbitalA == 8   && axis == 3 && valenceOrbitalB == 4) ||...
        (valenceOrbitalA == 8   && axis == 1 && valenceOrbitalB == 2) ||...
        (valenceOrbitalA == 8   && axis == 3 && valenceOrbitalB == 2) ||...
        (valenceOrbitalA == 8   && axis == 1 && valenceOrbitalB == 3) ||...
        (valenceOrbitalA == 8   && axis == 2 && valenceOrbitalB == 3) ||...
        (valenceOrbitalA == 9 && axis == 2 && valenceOrbitalB == 4) ||...
        (valenceOrbitalA == 9 && axis == 3 && valenceOrbitalB == 4) ||...
        (valenceOrbitalA == 9 && axis == 1 && valenceOrbitalB == 2) ||...
        (valenceOrbitalA == 9 && axis == 3 && valenceOrbitalB == 2) ||...
        (valenceOrbitalA == 9 && axis == 1 && valenceOrbitalB == 3) ||...
        (valenceOrbitalA == 9 && axis == 2 && valenceOrbitalB == 3) ||...
        (valenceOrbitalA == 7   && axis == 2 && valenceOrbitalB == 4) ||...
        (valenceOrbitalA == 7   && axis == 3 && valenceOrbitalB == 4) ||...
        (valenceOrbitalA == 7   && axis == 1 && valenceOrbitalB == 2) ||...
        (valenceOrbitalA == 7   && axis == 3 && valenceOrbitalB == 2) ||...
        (valenceOrbitalA == 7   && axis == 1 && valenceOrbitalB == 3) ||...
        (valenceOrbitalA == 7   && axis == 2 && valenceOrbitalB == 3) )
    if( (valenceOrbitalB == 2 && axis == 1) ||...
            (valenceOrbitalB == 4 && axis == 2) )
        dOrbital = 5;
    elseif( (valenceOrbitalB == 2 && axis == 3) ||...
            (valenceOrbitalB == 3 && axis == 2) )
        dOrbital = 6;
    elseif( (valenceOrbitalB == 4 && axis == 3) ||...
            (valenceOrbitalB == 3 && axis == 1) )
        dOrbital = 8;
    end
    overlapAOs1 = obj.GetGaussianOverlapAOs(atomTypeA,......
        valenceOrbitalA, ......
        gaussianExponentA, ......
        atomTypeB, ......
        valenceOrbitalB, ......
        gaussianExponentB,......
        dxyz, ...
        rAB,...
        overlapSASB);
    overlapAOs2 = obj.GetGaussianOverlapAOs(atomTypeA,......
        valenceOrbitalA, ......
        gaussianExponentA, ......
        atomTypeB, ......
        dOrbital, ...
        gaussianExponentB,......
        dxyz, ...
        rAB,...
        overlapSASB);
    value = overlapAOs2/(2.0*sqrt(gaussianExponentB))+xyzB(axis)*overlapAOs1;
elseif(valenceOrbitalA == 4 && axis == 1 && valenceOrbitalB == 9)
    overlapAOs1 = obj.GetGaussianOverlapAOs(atomTypeA,......
        valenceOrbitalA, ......
        gaussianExponentA, ......
        atomTypeB, ......
        valenceOrbitalB, ......
        gaussianExponentB,......
        dxyz, ...
        rAB,...
        overlapSASB);
    value = 0.5-2.0*gauMultAB*(dxyz(1)*dxyz(1))/gauPlusAB;
    value = value + 0.5*(gaussianExponentA*gaussianExponentA)*((dxyz(1)*dxyz(1))-(dxyz(2)*dxyz(2)))/gauPlusAB;
    value = value + (gauMultAB*dxyz(1)...
        *gauMultAB*dxyz(1))...
        *((dxyz(1)*dxyz(1))-(dxyz(2)*dxyz(2)))/(gauPlusAB*gauPlusAB);
    value = value .* 4.0*sqrt(gaussianExponentA)*gaussianExponentB/(gauPlusAB*gauPlusAB);
    value = value .* overlapSASB;
    value = value + xyzA(axis)*overlapAOs1;
elseif(valenceOrbitalA == 9 && axis == 1 && valenceOrbitalB == 4)
    overlapAOs1 = obj.GetGaussianOverlapAOs(atomTypeA,......
        valenceOrbitalA, ......
        gaussianExponentA, ......
        atomTypeB, ......
        valenceOrbitalB, ......
        gaussianExponentB,......
        dxyz, ...
        rAB,...
        overlapSASB);
    value = 0.5-2.0*gauMultAB*(dxyz(1)*dxyz(1))/gauPlusAB;
    value = value + 0.5*(gaussianExponentB*gaussianExponentB)*((dxyz(1)*dxyz(1))-(dxyz(2)*dxyz(2)))/gauPlusAB;
    value = value + (gauMultAB*dxyz(1)...
        *gauMultAB*dxyz(1))...
        *((dxyz(1)*dxyz(1))-(dxyz(2)*dxyz(2)))/(gauPlusAB*gauPlusAB);
    value = value .* 4.0*sqrt(gaussianExponentB)*gaussianExponentA/(gauPlusAB*gauPlusAB);
    value = value .* overlapSASB;
    value = value + xyzB(axis)*overlapAOs1;
elseif(valenceOrbitalA == 2 && axis == 2 && valenceOrbitalB == 9)
    overlapAOs1 = obj.GetGaussianOverlapAOs(atomTypeA,...
        valenceOrbitalA, ...
        gaussianExponentA, ...
        atomTypeB, ...
        valenceOrbitalB, ...
        gaussianExponentB,...
        dxyz, ...
        rAB,...
        overlapSASB);
    value = 0.5-2.0*gauMultAB*(dxyz(2)*dxyz(2))/gauPlusAB;
    value = value + 0.5*(gaussianExponentA*gaussianExponentA)*((dxyz(2)*dxyz(2))-(dxyz(1)*dxyz(1)))/gauPlusAB;
    value = value + (gauMultAB*dxyz(2)...
        *gauMultAB*dxyz(2))...
        *((dxyz(2)*dxyz(2))-(dxyz(1)*dxyz(1)))/(gauPlusAB*gauPlusAB);
    value = value .* (-4.0*sqrt(gaussianExponentA)*gaussianExponentB/(gauPlusAB*gauPlusAB));
    value = value .* overlapSASB;
    value = value + xyzA(axis)*overlapAOs1;
elseif(valenceOrbitalA == 9 && axis == 2 && valenceOrbitalB == 2)
    overlapAOs1 = obj.GetGaussianOverlapAOs(atomTypeA,...
        valenceOrbitalA, ...
        gaussianExponentA, ...
        atomTypeB, ...
        valenceOrbitalB, ...
        gaussianExponentB,...
        dxyz, ...
        rAB,...
        overlapSASB);
    value = 0.5-2.0*gauMultAB*(dxyz(2)*dxyz(2))/gauPlusAB;
    value = value + 0.5*(gaussianExponentB*gaussianExponentB)*((dxyz(2)*dxyz(2))-(dxyz(1)*dxyz(1)))/gauPlusAB;
    value = value + (gauMultAB*dxyz(2)...
        *gauMultAB*dxyz(2))...
        *((dxyz(2)*dxyz(2))-(dxyz(1)*dxyz(1)))/(gauPlusAB*gauPlusAB);
    value = value .* (-4.0*sqrt(gaussianExponentB)*gaussianExponentA/(gauPlusAB*gauPlusAB));
    value = value .* overlapSASB;
    value = value + xyzB(axis)*overlapAOs1;
elseif(valenceOrbitalA == 3 && axis == 3 && valenceOrbitalB == 9)
    overlapAOs1 = obj.GetGaussianOverlapAOs(atomTypeA,...
        valenceOrbitalA, ...
        gaussianExponentA, ...
        atomTypeB, ...
        valenceOrbitalB, ...
        gaussianExponentB,...
        dxyz, ...
        rAB,...
        overlapSASB);
    value = 0.5*((dxyz(1)*dxyz(1))-(dxyz(2)*dxyz(2)));
    value = value + gaussianExponentB*gaussianExponentB*dxyz(3)*dxyz(3)...
        *((dxyz(1)*dxyz(1))-(dxyz(2)*dxyz(2)))...
        /gauPlusAB;
    value = value .* 4.0*gaussianExponentA*gaussianExponentA*sqrt(gaussianExponentA)...
        *gaussianExponentB/(gauPlusAB*gauPlusAB*gauPlusAB);
    value = value .* overlapSASB;
    value = value + xyzA(axis)*overlapAOs1;
elseif(valenceOrbitalA == 9 && axis == 3 && valenceOrbitalB == 3)
    overlapAOs1 = obj.GetGaussianOverlapAOs(atomTypeA,...
        valenceOrbitalA, ...
        gaussianExponentA, ...
        atomTypeB, ...
        valenceOrbitalB, ...
        gaussianExponentB,...
        dxyz, ...
        rAB,...
        overlapSASB);
    value = 0.5*((dxyz(1)*dxyz(1))-(dxyz(2)*dxyz(2)));
    value = value + gaussianExponentA*gaussianExponentA*dxyz(3)*dxyz(3)...
        *((dxyz(1)*dxyz(1))-(dxyz(2)*dxyz(2)))...
        /gauPlusAB;
    value = value .* 4.0*gaussianExponentB*gaussianExponentB*sqrt(gaussianExponentB)...
        *gaussianExponentA/(gauPlusAB*gauPlusAB*gauPlusAB);
    value = value .* overlapSASB;
    value = value + xyzA(axis)*overlapAOs1;
elseif( (valenceOrbitalA == 4 && axis == 1 && valenceOrbitalB == 7) ||...
        (valenceOrbitalA == 2 && axis == 2 && valenceOrbitalB == 7) )
    overlapAOs1 = obj.GetGaussianOverlapAOs(atomTypeA,...
        valenceOrbitalA, ...
        gaussianExponentA, ...
        atomTypeB, ...
        valenceOrbitalB, ...
        gaussianExponentB,...
        dxyz, ...
        rAB,...
        overlapSASB);
    value = -0.5...
        +2.0*gauMultAB*(dxyz(axis)*dxyz(axis))/gauPlusAB...
        +0.5*(gaussianExponentA*gaussianExponentA)...
        *(2.0*(dxyz(3)*dxyz(3))-(dxyz(1)*dxyz(1))-(dxyz(2)*dxyz(2)))/gauPlusAB...
        +(gauMultAB*gauMultAB*dxyz(axis)*dxyz(axis)/(gauPlusAB*gauPlusAB))...
        *(2.0*(dxyz(3)*dxyz(3))-(dxyz(1)*dxyz(1))-(dxyz(2)*dxyz(2)));
    value = value .* 4.0*sqrt(gaussianExponentA)*gaussianExponentB/(gauPlusAB*gauPlusAB*sqrt(3.0));
    value = value .* overlapSASB;
    value = value + xyzA(axis)*overlapAOs1;
elseif( (valenceOrbitalA == 7 && axis == 1 && valenceOrbitalB == 4) ||...
        (valenceOrbitalA == 7 && axis == 2 && valenceOrbitalB == 2) )
    overlapAOs1 = obj.GetGaussianOverlapAOs(atomTypeA,...
        valenceOrbitalA, ...
        gaussianExponentA, ...
        atomTypeB, ...
        valenceOrbitalB, ...
        gaussianExponentB,...
        dxyz, ...
        rAB,...
        overlapSASB);
    value = -0.5...
        +2.0*gauMultAB*(dxyz(axis)*dxyz(axis))/gauPlusAB...
        +0.5*(gaussianExponentB*gaussianExponentB)...
        *(2.0*(dxyz(3)*dxyz(3))-(dxyz(1)*dxyz(1))-(dxyz(2)*dxyz(2)))/gauPlusAB...
        +(gauMultAB*gauMultAB*dxyz(axis)*dxyz(axis)/(gauPlusAB*gauPlusAB))...
        *(2.0*(dxyz(3)*dxyz(3))-(dxyz(1)*dxyz(1))-(dxyz(2)*dxyz(2)));
    value = value .* 4.0*sqrt(gaussianExponentB)*gaussianExponentA/(gauPlusAB*gauPlusAB*sqrt(3.0));
    value = value .* overlapSASB;
    value = value + xyzB(axis)*overlapAOs1;
elseif(valenceOrbitalA == 3 && axis == 3 && valenceOrbitalB == 7)
    overlapAOs1 = obj.GetGaussianOverlapAOs(atomTypeA,...
        valenceOrbitalA, ...
        gaussianExponentA, ...
        atomTypeB, ...
        valenceOrbitalB, ...
        gaussianExponentB,...
        dxyz, ...
        rAB,...
        overlapSASB);
    value = 1.0...
        -4.0*gauMultAB*(dxyz(axis)*dxyz(axis))/gauPlusAB...
        +0.5*(gaussianExponentA*gaussianExponentA)...
        *(2.0*(dxyz(3)*dxyz(3))-(dxyz(1)*dxyz(1))-(dxyz(2)*dxyz(2)))/gauPlusAB...
        +(gauMultAB*gauMultAB*dxyz(axis)*dxyz(axis)/(gauPlusAB*gauPlusAB))...
        *(2.0*(dxyz(3)*dxyz(3))-(dxyz(1)*dxyz(1))-(dxyz(2)*dxyz(2)));
    value = value .* 4.0*sqrt(gaussianExponentA)*gaussianExponentB/(gauPlusAB*gauPlusAB*sqrt(3.0));
    value = value .* overlapSASB;
    value = value + xyzA(axis)*overlapAOs1;
elseif(valenceOrbitalA == 7 && axis == 3 && valenceOrbitalB == 3)
    overlapAOs1 = obj.GetGaussianOverlapAOs(atomTypeA,...
        valenceOrbitalA, ...
        gaussianExponentA, ...
        atomTypeB, ...
        valenceOrbitalB, ...
        gaussianExponentB,...
        dxyz, ...
        rAB,...
        overlapSASB);
    value = 1.0...
        -4.0*gauMultAB*(dxyz(axis)*dxyz(axis))/gauPlusAB...
        +0.5*(gaussianExponentB*gaussianExponentB)...
        *(2.0*(dxyz(3)*dxyz(3))-(dxyz(1)*dxyz(1))-(dxyz(2)*dxyz(2)))/gauPlusAB...
        +(gauMultAB*gauMultAB*dxyz(axis)*dxyz(axis)/(gauPlusAB*gauPlusAB))...
        *(2.0*(dxyz(3)*dxyz(3))-(dxyz(1)*dxyz(1))-(dxyz(2)*dxyz(2)));
    value = value .* 4.0*sqrt(gaussianExponentB)*gaussianExponentA/(gauPlusAB*gauPlusAB*sqrt(3.0));
    value = value .* overlapSASB;
    value = value + xyzB(axis)*overlapAOs1;
elseif( (valenceOrbitalA == 5 && axis == 1 && valenceOrbitalB == valenceOrbitalA) ||...
        (valenceOrbitalA == 5 && axis == 2 && valenceOrbitalB == valenceOrbitalA) ||...
        (valenceOrbitalA == 6 && axis == 2 && valenceOrbitalB == valenceOrbitalA) ||...
        (valenceOrbitalA == 6 && axis == 3 && valenceOrbitalB == valenceOrbitalA) ||...
        (valenceOrbitalA == 8 && axis == 3 && valenceOrbitalB == valenceOrbitalA) ||...
        (valenceOrbitalA == 8 && axis == 1 && valenceOrbitalB == valenceOrbitalA) )
    if(valenceOrbitalB == 5)
        if(axis == 1)
            anotherAxis = 2;
        else
            anotherAxis = 1;
        end
    elseif(valenceOrbitalB == 6)
        if(axis == 2)
            anotherAxis = 3;
        else
            anotherAxis = 2;
        end
    elseif(valenceOrbitalB == 8)
        if(axis == 3)
            anotherAxis = 1;
        else
            anotherAxis = 3;
        end
    end
    axisAverage = (gaussianExponentA*xyzA(axis)+gaussianExponentB*xyzB(axis))/gauPlusAB;
    overlapAOs1 = obj.GetGaussianOverlapAOs(atomTypeA,...
        valenceOrbitalA, ...
        gaussianExponentA, ...
        atomTypeB, ...
        valenceOrbitalB, ...
        gaussianExponentB,...
        dxyz, ...
        rAB,...
        overlapSASB);
    gauMinsAB = gaussianExponentA-gaussianExponentB;
    value = 0.5*gauMinsAB*dxyz(axis)...
        +gauMinsAB*gauMultAB...
        *dxyz(axis)*(dxyz(anotherAxis)*dxyz(anotherAxis))/gauPlusAB;
    value = value .* 8.0*gauMultAB/(gauPlusAB*gauPlusAB*gauPlusAB);
    value = value .* overlapSASB;
    value = value + axisAverage*overlapAOs1;
elseif( (valenceOrbitalA == 5   && axis == 3 && valenceOrbitalB == valenceOrbitalA) ||...
        (valenceOrbitalA == 6   && axis == 1 && valenceOrbitalB == valenceOrbitalA) ||...
        (valenceOrbitalA == 8   && axis == 2 && valenceOrbitalB == valenceOrbitalA) ||...
        (valenceOrbitalA == 9 && axis == 3 && valenceOrbitalB == valenceOrbitalA) )
    axisAverage = (gaussianExponentA*xyzA(axis)+gaussianExponentB*xyzB(axis))/gauPlusAB;
    overlapAOs1 = obj.GetGaussianOverlapAOs(atomTypeA,...
        valenceOrbitalA, ...
        gaussianExponentA, ...
        atomTypeB, ...
        valenceOrbitalB, ...
        gaussianExponentB,...
        dxyz, ...
        rAB,...
        overlapSASB);
    value = axisAverage*overlapAOs1;
elseif( (valenceOrbitalA == 9 && axis == 1 && valenceOrbitalB == valenceOrbitalA) ||...
        (valenceOrbitalA == 9 && axis == 2 && valenceOrbitalB == valenceOrbitalA) )
    if(axis == 1)
        anotherAxis = 2;
    else
        anotherAxis = 1;
    end
    axisAverage = (gaussianExponentA*xyzA(axis)+gaussianExponentB*xyzB(axis))/gauPlusAB;
    overlapAOs1 = obj.GetGaussianOverlapAOs(atomTypeA,...
        valenceOrbitalA, ...
        gaussianExponentA, ...
        atomTypeB, ...
        valenceOrbitalB, ...
        gaussianExponentB,...
        dxyz, ...
        rAB,...
        overlapSASB);
    gauMinsAB = gaussianExponentA-gaussianExponentB;
    value = gauMinsAB*dxyz(axis)...
        -gauMinsAB*gauMultAB...
        *((dxyz(axis)*dxyz(axis)) - (dxyz(anotherAxis)*dxyz(anotherAxis)))*dxyz(axis)/gauPlusAB;
    value = value .* 4.0*gauMultAB/(gauPlusAB*gauPlusAB*gauPlusAB);
    value = value .* overlapSASB;
    value = value + axisAverage*overlapAOs1;
elseif( (valenceOrbitalA == 7 && axis == 1 && valenceOrbitalB == valenceOrbitalA) ||...
        (valenceOrbitalA == 7 && axis == 2 && valenceOrbitalB == valenceOrbitalA) )
    axisAverage = (gaussianExponentA*xyzA(axis)+gaussianExponentB*xyzB(axis))/gauPlusAB;
    overlapAOs1 = obj.GetGaussianOverlapAOs(atomTypeA,...
        valenceOrbitalA, ...
        gaussianExponentA, ...
        atomTypeB, ...
        valenceOrbitalB, ...
        gaussianExponentB,...
        dxyz, ...
        rAB,...
        overlapSASB);
    gauMinsAB = gaussianExponentA-gaussianExponentB;
    value = gauMinsAB*dxyz(axis)...
        -gauMinsAB*gauMultAB...
        *(2.0*(dxyz(3)*dxyz(3)) - (dxyz(1)*dxyz(1)) - (dxyz(2)*dxyz(2)))*dxyz(axis)/gauPlusAB;
    value = value .* 4.0*gauMultAB/(3.0*gauPlusAB*gauPlusAB*gauPlusAB);
    value = value .* overlapSASB;
    value = value + axisAverage*overlapAOs1;
elseif( valenceOrbitalA == 7 && axis == 3 && valenceOrbitalB == valenceOrbitalA)
    axisAverage = (gaussianExponentA*xyzA(axis)+gaussianExponentB*xyzB(axis))/gauPlusAB;
    overlapAOs1 = obj.GetGaussianOverlapAOs(atomTypeA,...
        valenceOrbitalA, ...
        gaussianExponentA, ...
        atomTypeB, ...
        valenceOrbitalB, ...
        gaussianExponentB,...
        dxyz, ...
        rAB,...
        overlapSASB);
    gauMinsAB = gaussianExponentA-gaussianExponentB;
    value = 2.0*gauMinsAB*dxyz(axis)...
        -gauMinsAB*gauMultAB...
        *(2.0*(dxyz(3)*dxyz(3)) - (dxyz(1)*dxyz(1)) - (dxyz(2)*dxyz(2)))*dxyz(axis)/gauPlusAB;
    value = value .* 8.0*gauMultAB/(3.0*gauPlusAB*gauPlusAB*gauPlusAB);
    value = value .* overlapSASB;
    value = value + axisAverage*overlapAOs1;
elseif( (valenceOrbitalA == 5 && axis == 2 && valenceOrbitalB == 6) ||...
        (valenceOrbitalA == 6 && axis == 3 && valenceOrbitalB == 8) ||...
        (valenceOrbitalA == 8 && axis == 1 && valenceOrbitalB == 5) ||...
        (valenceOrbitalA == 6 && axis == 2 && valenceOrbitalB == 5) ||...
        (valenceOrbitalA == 8 && axis == 3 && valenceOrbitalB == 6) ||...
        (valenceOrbitalA == 5 && axis == 1 && valenceOrbitalB == 8) )
    axisAverage = (gaussianExponentA*xyzA(axis)+gaussianExponentB*xyzB(axis))/gauPlusAB;
    overlapAOs1 = obj.GetGaussianOverlapAOs(atomTypeA,...
        valenceOrbitalA, ...
        gaussianExponentA, ...
        atomTypeB, ...
        valenceOrbitalB, ...
        gaussianExponentB,...
        dxyz, ...
        rAB,...
        overlapSASB);
    gauMinsAB = gaussianExponentA-gaussianExponentB;
    value = -8.0*(gaussianExponentA*gauMultAB*gaussianExponentB)*dxyz(1)*dxyz(2)*dxyz(3)...
        *gauMinsAB/(gauPlusAB*gauPlusAB*gauPlusAB*gauPlusAB);
    value = value .* overlapSASB;
    value = value + axisAverage*overlapAOs1;
    
    
elseif( (valenceOrbitalA == 5 && axis == 1 && valenceOrbitalB == 6) ||...
        (valenceOrbitalA == 6 && axis == 2 && valenceOrbitalB == 8) ||...
        (valenceOrbitalA == 8 && axis == 3 && valenceOrbitalB == 5) ||...
        (valenceOrbitalA == 6 && axis == 3 && valenceOrbitalB == 5) ||...
        (valenceOrbitalA == 8 && axis == 1 && valenceOrbitalB == 6) ||...
        (valenceOrbitalA == 5 && axis == 2 && valenceOrbitalB == 8) )
    if(valenceOrbitalA == 5 && valenceOrbitalB == 6)
        anotherAxis1 = 2;
        anotherAxis2 = 3;
    elseif(valenceOrbitalA == 6 && valenceOrbitalB == 8)
        anotherAxis1 = 3;
        anotherAxis2 = 1;
    elseif(valenceOrbitalA == 8 && valenceOrbitalB == 5)
        anotherAxis1 = 1;
        anotherAxis2 = 2;
    elseif(valenceOrbitalA == 6 && valenceOrbitalB == 5)
        anotherAxis1 = 2;
        anotherAxis2 = 1;
    elseif(valenceOrbitalA == 8 && valenceOrbitalB == 6)
        anotherAxis1 = 3;
        anotherAxis2 = 2;
    elseif(valenceOrbitalA == 5 && valenceOrbitalB == 8)
        anotherAxis1 = 1;
        anotherAxis2 = 3;
    end
    axisAverage = (gaussianExponentA*xyzA(axis)+gaussianExponentB*xyzB(axis))/gauPlusAB;
    overlapAOs1 = obj.GetGaussianOverlapAOs(atomTypeA,...
        valenceOrbitalA, ...
        gaussianExponentA, ...
        atomTypeB, ...
        valenceOrbitalB, ...
        gaussianExponentB,...
        dxyz, ...
        rAB,...
        overlapSASB);
    value = 0.5-gauMultAB*dxyz(anotherAxis1)*dxyz(anotherAxis1)/gauPlusAB;
    value = value .* 8.0*(gaussianExponentA*gaussianExponentA)*gaussianExponentB*dxyz(anotherAxis2)/(gauPlusAB*gauPlusAB*gauPlusAB);
    value = value .* overlapSASB;
    value = value + axisAverage*overlapAOs1;
elseif( (valenceOrbitalA == 6 && axis == 1 && valenceOrbitalB == 5) ||...
        (valenceOrbitalA == 8 && axis == 2 && valenceOrbitalB == 6) ||...
        (valenceOrbitalA == 5 && axis == 3 && valenceOrbitalB == 8) ||...
        (valenceOrbitalA == 5 && axis == 3 && valenceOrbitalB == 6) ||...
        (valenceOrbitalA == 6 && axis == 1 && valenceOrbitalB == 8) ||...
        (valenceOrbitalA == 8 && axis == 2 && valenceOrbitalB == 5) )
    if(valenceOrbitalA == 6 && valenceOrbitalB == 5)
        anotherAxis1 = 2;
        anotherAxis2 = 3;
    elseif(valenceOrbitalA == 8 && valenceOrbitalB == 6)
        anotherAxis1 = 3;
        anotherAxis2 = 1;
    elseif(valenceOrbitalA == 5 && valenceOrbitalB == 8)
        anotherAxis1 = 1;
        anotherAxis2 = 2;
    elseif(valenceOrbitalA == 5 && valenceOrbitalB == 6)
        anotherAxis1 = 2;
        anotherAxis2 = 1;
    elseif(valenceOrbitalA == 6 && valenceOrbitalB == 8)
        anotherAxis1 = 3;
        anotherAxis2 = 2;
    elseif(valenceOrbitalA == 8 && valenceOrbitalB == 5)
        anotherAxis1 = 1;
        anotherAxis2 = 3;
    end
    axisAverage = (gaussianExponentA*xyzA(axis)+gaussianExponentB*xyzB(axis))/gauPlusAB;
    overlapAOs1 = obj.GetGaussianOverlapAOs(atomTypeA,...
        valenceOrbitalA, ...
        gaussianExponentA, ...
        atomTypeB, ...
        valenceOrbitalB, ...
        gaussianExponentB,...
        dxyz, ...
        rAB,...
        overlapSASB);
    value = 0.5-gauMultAB*dxyz(anotherAxis1)*dxyz(anotherAxis1)/gauPlusAB;
    value = value .* (-8.0*(gaussianExponentB*gaussianExponentB)*gaussianExponentA*dxyz(anotherAxis2)/(gauPlusAB*gauPlusAB*gauPlusAB));
    value = value .* overlapSASB;
    value = value + axisAverage*overlapAOs1;
elseif(valenceOrbitalA == 9 && axis == 1 && valenceOrbitalB == 5)
    axisAverage = (gaussianExponentA*xyzA(axis)+gaussianExponentB*xyzB(axis))/gauPlusAB;
    overlapAOs1 = obj.GetGaussianOverlapAOs(atomTypeA,...
        valenceOrbitalA, ...
        gaussianExponentA, ...
        atomTypeB, ...
        valenceOrbitalB, ...
        gaussianExponentB,...
        dxyz, ...
        rAB,...
        overlapSASB);
    value = 0.5*gauPlusAB...
        -(gaussianExponentA*gaussianExponentA)*gaussianExponentB*(dxyz(1)*dxyz(1))/gauPlusAB...
        +(gaussianExponentB*gaussianExponentB)*gaussianExponentA...
        *((dxyz(1)*dxyz(1))-(dxyz(2)*dxyz(2)))/(2.0*gauPlusAB);
    value = value .* 8.0*gauMultAB*dxyz(2)/(gauPlusAB*gauPlusAB*gauPlusAB);
    value = value .* overlapSASB;
    value = value + axisAverage*overlapAOs1;
elseif(valenceOrbitalA == 5 && axis == 1 && valenceOrbitalB == 9)
    axisAverage = (gaussianExponentA*xyzA(axis)+gaussianExponentB*xyzB(axis))/gauPlusAB;
    overlapAOs1 = obj.GetGaussianOverlapAOs(atomTypeA,...
        valenceOrbitalA, ...
        gaussianExponentA, ...
        atomTypeB, ...
        valenceOrbitalB, ...
        gaussianExponentB,...
        dxyz, ...
        rAB,...
        overlapSASB);
    value = 0.5*gauPlusAB...
        -(gaussianExponentB*gaussianExponentB)*gaussianExponentA*(dxyz(1)*dxyz(1))/gauPlusAB...
        +(gaussianExponentA*gaussianExponentA)*gaussianExponentB...
        *((dxyz(1)*dxyz(1))-(dxyz(2)*dxyz(2)))/(2.0*gauPlusAB);
    value = value .* (-8.0*gauMultAB*dxyz(2)/(gauPlusAB*gauPlusAB*gauPlusAB));
    value = value .* overlapSASB;
    value = value + axisAverage*overlapAOs1;
elseif(valenceOrbitalA == 9 && axis == 2 && valenceOrbitalB == 5)
    axisAverage = (gaussianExponentA*xyzA(axis)+gaussianExponentB*xyzB(axis))/gauPlusAB;
    overlapAOs1 = obj.GetGaussianOverlapAOs(atomTypeA,...
        valenceOrbitalA, ...
        gaussianExponentA, ...
        atomTypeB, ...
        valenceOrbitalB, ...
        gaussianExponentB,...
        dxyz, ...
        rAB,...
        overlapSASB);
    value = -0.5*gauPlusAB...
        +(gaussianExponentA*gaussianExponentA)*gaussianExponentB*(dxyz(2)*dxyz(2))/gauPlusAB...
        +(gaussianExponentB*gaussianExponentB)*gaussianExponentA...
        *((dxyz(1)*dxyz(1))-(dxyz(2)*dxyz(2)))/(2.0*gauPlusAB);
    value = value .* 8.0*gauMultAB*dxyz(1)/(gauPlusAB*gauPlusAB*gauPlusAB);
    value = value .* overlapSASB;
    value = value + axisAverage*overlapAOs1;
elseif(valenceOrbitalA == 5 && axis == 2 && valenceOrbitalB == 9)
    axisAverage = (gaussianExponentA*xyzA(axis)+gaussianExponentB*xyzB(axis))/gauPlusAB;
    overlapAOs1 = obj.GetGaussianOverlapAOs(atomTypeA,...
        valenceOrbitalA, ...
        gaussianExponentA, ...
        atomTypeB, ...
        valenceOrbitalB, ...
        gaussianExponentB,...
        dxyz, ...
        rAB,...
        overlapSASB);
    value = -0.5*gauPlusAB...
        +(gaussianExponentB*gaussianExponentB)*gaussianExponentA*(dxyz(2)*dxyz(2))/gauPlusAB...
        +(gaussianExponentA*gaussianExponentA)*gaussianExponentB...
        *((dxyz(1)*dxyz(1))-(dxyz(2)*dxyz(2)))/(2.0*gauPlusAB);
    value = value .* (-8.0*gauMultAB*dxyz(1)/(gauPlusAB*gauPlusAB*gauPlusAB));
    value = value .* overlapSASB;
    value = value + axisAverage*overlapAOs1;
elseif( (valenceOrbitalA == 9 && axis == 1 && valenceOrbitalB == 6) ||...
        (valenceOrbitalA == 9 && axis == 2 && valenceOrbitalB == 8) ||...
        (valenceOrbitalA == 9 && axis == 3 && valenceOrbitalB == 5) )
    overlapAOs1 = obj.GetGaussianOverlapAOs(atomTypeA,...
        valenceOrbitalA, ...
        gaussianExponentA, ...
        atomTypeB, ...
        valenceOrbitalB, ...
        gaussianExponentB,...
        dxyz, ...
        rAB,...
        overlapSASB);
    value = 8.0*(gaussianExponentA*gaussianExponentA*gaussianExponentA*gaussianExponentA)...
        *(gaussianExponentB*gaussianExponentB*gaussianExponentB)...
        *dxyz(1)*dxyz(2)*dxyz(3)...
        *((dxyz(1)*dxyz(1))-(dxyz(2)*dxyz(2)))...
        /(gauPlusAB*gauPlusAB*gauPlusAB*gauPlusAB*gauPlusAB);
    value = value .* overlapSASB;
    value = value + xyzB(axis)*overlapAOs1;
elseif( (valenceOrbitalA == 6 && axis == 1 && valenceOrbitalB == 9) ||...
        (valenceOrbitalA == 8 && axis == 2 && valenceOrbitalB == 9) ||...
        (valenceOrbitalA == 5 && axis == 3 && valenceOrbitalB == 9) )
    overlapAOs1 = obj.GetGaussianOverlapAOs(atomTypeA,...
        valenceOrbitalA, ...
        gaussianExponentA, ...
        atomTypeB, ...
        valenceOrbitalB, ...
        gaussianExponentB,...
        dxyz, ...
        rAB,...
        overlapSASB);
    value = -8.0*(gaussianExponentA*gaussianExponentA*gaussianExponentA)...
        *(gaussianExponentB*gaussianExponentB*gaussianExponentB*gaussianExponentB)...
        *dxyz(1)*dxyz(2)*dxyz(3)...
        *((dxyz(1)*dxyz(1))-(dxyz(2)*dxyz(2)))...
        /(gauPlusAB*gauPlusAB*gauPlusAB*gauPlusAB*gauPlusAB);
    value = value .* overlapSASB;
    value = value + xyzA(axis)*overlapAOs1;
elseif(valenceOrbitalA == 9 && axis == 2 && valenceOrbitalB == 6)
    axisAverage = (gaussianExponentA*xyzA(axis)+gaussianExponentB*xyzB(axis))/gauPlusAB;
    overlapAOs1 = obj.GetGaussianOverlapAOs(atomTypeA,...
        valenceOrbitalA, ...
        gaussianExponentA, ...
        atomTypeB, ...
        valenceOrbitalB, ...
        gaussianExponentB,...
        dxyz, ...
        rAB,...
        overlapSASB);
    value = -0.5*gaussianExponentA...
        +(gaussianExponentA*gaussianExponentA)*gaussianExponentB*(dxyz(2)*dxyz(2))/gauPlusAB...
        +(gaussianExponentB*gaussianExponentB)*gaussianExponentA...
        *((dxyz(1)*dxyz(1))-(dxyz(2)*dxyz(2)))/(2.0*gauPlusAB);
    value = value .* 8.0*gauMultAB*dxyz(3)/(gauPlusAB*gauPlusAB*gauPlusAB);
    value = value .* overlapSASB;
    value = value + axisAverage*overlapAOs1;
elseif(valenceOrbitalA == 6 && axis == 2 && valenceOrbitalB == 9)
    axisAverage = (gaussianExponentA*xyzA(axis)+gaussianExponentB*xyzB(axis))/gauPlusAB;
    overlapAOs1 = obj.GetGaussianOverlapAOs(atomTypeA,...
        valenceOrbitalA, ...
        gaussianExponentA, ...
        atomTypeB, ...
        valenceOrbitalB, ...
        gaussianExponentB,...
        dxyz, ...
        rAB,...
        overlapSASB);
    value = -0.5*gaussianExponentB...
        +(gaussianExponentB*gaussianExponentB)*gaussianExponentA*(dxyz(2)*dxyz(2))/gauPlusAB...
        +(gaussianExponentA*gaussianExponentA)*gaussianExponentB...
        *((dxyz(1)*dxyz(1))-(dxyz(2)*dxyz(2)))/(2.0*gauPlusAB);
    value = value .* (-8.0*gauMultAB*dxyz(3)/(gauPlusAB*gauPlusAB*gauPlusAB));
    value = value .* overlapSASB;
    value = value + axisAverage*overlapAOs1;
elseif(valenceOrbitalA == 9 && axis == 1 && valenceOrbitalB == 8)
    axisAverage = (gaussianExponentA*xyzA(axis)+gaussianExponentB*xyzB(axis))/gauPlusAB;
    overlapAOs1 = obj.GetGaussianOverlapAOs(atomTypeA,...
        valenceOrbitalA, ...
        gaussianExponentA, ...
        atomTypeB, ...
        valenceOrbitalB, ...
        gaussianExponentB,...
        dxyz, ...
        rAB,...
        overlapSASB);
    value = -0.5*gaussianExponentA...
        +(gaussianExponentA*gaussianExponentA)*gaussianExponentB*(dxyz(1)*dxyz(1))/gauPlusAB...
        +(gaussianExponentB*gaussianExponentB)*gaussianExponentA...
        *((dxyz(2)*dxyz(2))-(dxyz(1)*dxyz(1)))/(2.0*gauPlusAB);
    value = value .* (-8.0*gauMultAB*dxyz(3)/(gauPlusAB*gauPlusAB*gauPlusAB));
    value = value .* overlapSASB;
    value = value + axisAverage*overlapAOs1;
elseif(valenceOrbitalA == 8 && axis == 1 && valenceOrbitalB == 9)
    axisAverage = (gaussianExponentA*xyzA(axis)+gaussianExponentB*xyzB(axis))/gauPlusAB;
    overlapAOs1 = obj.GetGaussianOverlapAOs(atomTypeA,...
        valenceOrbitalA, ...
        gaussianExponentA, ...
        atomTypeB, ...
        valenceOrbitalB, ...
        gaussianExponentB,...
        dxyz, ...
        rAB,...
        overlapSASB);
    value = -0.5*gaussianExponentB...
        +(gaussianExponentB*gaussianExponentB)*gaussianExponentA*(dxyz(2)*dxyz(2))/gauPlusAB...
        +(gaussianExponentA*gaussianExponentA)*gaussianExponentB...
        *((dxyz(2)*dxyz(2))-(dxyz(1)*dxyz(1)))/(2.0*gauPlusAB);
    value = value .* 8.0*gauMultAB*dxyz(3)/(gauPlusAB*gauPlusAB*gauPlusAB);
    value = value .* overlapSASB;
    value = value + axisAverage*overlapAOs1;
elseif(valenceOrbitalA == 9 && axis == 3 && valenceOrbitalB == 6)
    axisAverage = (gaussianExponentA*xyzA(axis)+gaussianExponentB*xyzB(axis))/gauPlusAB;
    overlapAOs1 = obj.GetGaussianOverlapAOs(atomTypeA,...
        valenceOrbitalA, ...
        gaussianExponentA, ...
        atomTypeB, ...
        valenceOrbitalB, ...
        gaussianExponentB,...
        dxyz, ...
        rAB,...
        overlapSASB);
    value = gauMultAB*((dxyz(1)*dxyz(1))-(dxyz(2)*dxyz(2)))/gauPlusAB+1.0;
    value = value .* 4.0*gaussianExponentA*(gaussianExponentB*gaussianExponentB)*dxyz(2)/(gauPlusAB*gauPlusAB*gauPlusAB);
    value = value .* overlapSASB;
    value = value + axisAverage*overlapAOs1;
elseif(valenceOrbitalA == 6 && axis == 3 && valenceOrbitalB == 9)
    axisAverage = (gaussianExponentA*xyzA(axis)+gaussianExponentB*xyzB(axis))/gauPlusAB;
    overlapAOs1 = obj.GetGaussianOverlapAOs(atomTypeA,...
        valenceOrbitalA, ...
        gaussianExponentA, ...
        atomTypeB, ...
        valenceOrbitalB, ...
        gaussianExponentB,...
        dxyz, ...
        rAB,...
        overlapSASB);
    value = gauMultAB*((dxyz(1)*dxyz(1))-(dxyz(2)*dxyz(2)))/gauPlusAB+1.0;
    value = value .* (-4.0*gaussianExponentB*(gaussianExponentA*gaussianExponentA)*dxyz(2)/(gauPlusAB*gauPlusAB*gauPlusAB));
    value = value .* overlapSASB;
    value = value + axisAverage*overlapAOs1;
elseif(valenceOrbitalA == 9 && axis == 3 && valenceOrbitalB == 8)
    axisAverage = (gaussianExponentA*xyzA(axis)+gaussianExponentB*xyzB(axis))/gauPlusAB;
    overlapAOs1 = obj.GetGaussianOverlapAOs(atomTypeA,...
        valenceOrbitalA, ...
        gaussianExponentA, ...
        atomTypeB, ...
        valenceOrbitalB, ...
        gaussianExponentB,...
        dxyz, ...
        rAB,...
        overlapSASB);
    value = gauMultAB*((dxyz(2)*dxyz(2))-(dxyz(1)*dxyz(1)))/gauPlusAB+1.0;
    value = value .* (-4.0*gaussianExponentA*(gaussianExponentB*gaussianExponentB)*dxyz(1)/(gauPlusAB*gauPlusAB*gauPlusAB));
    value = value .* overlapSASB;
    value = value + axisAverage*overlapAOs1;
elseif(valenceOrbitalA == 8 && axis == 3 && valenceOrbitalB == 9)
    axisAverage = (gaussianExponentA*xyzA(axis)+gaussianExponentB*xyzB(axis))/gauPlusAB;
    overlapAOs1 = obj.GetGaussianOverlapAOs(atomTypeA,...
        valenceOrbitalA, ...
        gaussianExponentA, ...
        atomTypeB, ...
        valenceOrbitalB, ...
        gaussianExponentB,...
        dxyz, ...
        rAB,...
        overlapSASB);
    value = gauMultAB*((dxyz(2)*dxyz(2))-(dxyz(1)*dxyz(1)))/gauPlusAB+1.0;
    value = value .* 4.0*gaussianExponentB*(gaussianExponentA*gaussianExponentA)*dxyz(1)/(gauPlusAB*gauPlusAB*gauPlusAB);
    value = value .* overlapSASB;
    value = value + axisAverage*overlapAOs1;
elseif( (valenceOrbitalA == 7 && axis == 1 && valenceOrbitalB == 6) ||...
        (valenceOrbitalA == 7 && axis == 2 && valenceOrbitalB == 8) ||...
        (valenceOrbitalA == 7 && axis == 3 && valenceOrbitalB == 5) )
    overlapAOs1 = obj.GetGaussianOverlapAOs(atomTypeA,...
        valenceOrbitalA, ...
        gaussianExponentA, ...
        atomTypeB, ...
        valenceOrbitalB, ...
        gaussianExponentB,...
        dxyz, ...
        rAB,...
        overlapSASB);
    value = 2.0*(dxyz(3)*dxyz(3)) - (dxyz(1)*dxyz(1)) - (dxyz(2)*dxyz(2));
    value = value .* dxyz(1)*dxyz(2)*dxyz(3);
    value = value .* 8.0*(gaussianExponentA*gaussianExponentA*gaussianExponentA*gaussianExponentA)...
        *(gaussianExponentB*gaussianExponentB*gaussianExponentB);
    value = value ./ ((sqrt(3.0)*(gauPlusAB*gauPlusAB*gauPlusAB*gauPlusAB*gauPlusAB)));
    value = value .* overlapSASB;
    value = value + xyzB(axis)*overlapAOs1;
elseif( (valenceOrbitalA == 6 && axis == 1 && valenceOrbitalB == 7) ||...
        (valenceOrbitalA == 8 && axis == 2 && valenceOrbitalB == 7) ||...
        (valenceOrbitalA == 5 && axis == 3 && valenceOrbitalB == 7) )
    overlapAOs1 = obj.GetGaussianOverlapAOs(atomTypeA,...
        valenceOrbitalA, ...
        gaussianExponentA, ...
        atomTypeB, ...
        valenceOrbitalB, ...
        gaussianExponentB,...
        dxyz, ...
        rAB,...
        overlapSASB);
    value = 2.0*(dxyz(3)*dxyz(3)) - (dxyz(1)*dxyz(1)) - (dxyz(2)*dxyz(2));
    value = value .* dxyz(1)*dxyz(2)*dxyz(3);
    value = value .* (-8.0*(gaussianExponentB*gaussianExponentB*gaussianExponentB*gaussianExponentB)*(gaussianExponentA*gaussianExponentA*gaussianExponentA));
    value = value ./ (sqrt(3.0)*(gauPlusAB*gauPlusAB*gauPlusAB*gauPlusAB*gauPlusAB));
    value = value .* overlapSASB;
    value = value + xyzA(axis)*overlapAOs1;
elseif( (valenceOrbitalA == 7 && axis == 1 && valenceOrbitalB == 5) ||...
        (valenceOrbitalA == 7 && axis == 2 && valenceOrbitalB == 5) )
    if(axis == 1)
        anotherAxis = 2;
    elseif(axis == 2)
        anotherAxis = 1;
    end
    overlapAOs1 = obj.GetGaussianOverlapAOs(atomTypeA,...
        valenceOrbitalA, ...
        gaussianExponentA, ...
        atomTypeB, ...
        valenceOrbitalB, ...
        gaussianExponentB,...
        dxyz, ...
        rAB,...
        overlapSASB);
    value = 0.5*(gaussianExponentB-gaussianExponentA)...
        +3.0*(gaussianExponentA*gaussianExponentA)*gaussianExponentB...
        *(dxyz(axis)*dxyz(axis))/(gauPlusAB*gauPlusAB)...
        +gaussianExponentA*(gaussianExponentB*gaussianExponentB)...
        *(2.0*(dxyz(3)*dxyz(3)) - (dxyz(1)*dxyz(1)) - (dxyz(2)*dxyz(2)))/(2.0*gauPlusAB)...
        +(gaussianExponentA*gaussianExponentA*gaussianExponentA)*(gaussianExponentB*gaussianExponentB)*(dxyz(axis)*dxyz(axis))...
        *(2.0*(dxyz(3)*dxyz(3)) - (dxyz(1)*dxyz(1)) - (dxyz(2)*dxyz(2)))...
        /(gauPlusAB*gauPlusAB);
    value = value .* 8.0*gauMultAB*dxyz(anotherAxis)/(sqrt(3.0)*gauPlusAB*gauPlusAB*gauPlusAB);
    value = value .* overlapSASB;
    value = value + xyzB(axis)*overlapAOs1;
elseif( (valenceOrbitalA == 5 && axis == 1 && valenceOrbitalB == 7) ||...
        (valenceOrbitalA == 5 && axis == 2 && valenceOrbitalB == 7) )
    if(axis == 1)
        anotherAxis = 2;
    elseif(axis == 2)
        anotherAxis = 1;
    end
    overlapAOs1 = obj.GetGaussianOverlapAOs(atomTypeA,...
        valenceOrbitalA, ...
        gaussianExponentA, ...
        atomTypeB, ...
        valenceOrbitalB, ...
        gaussianExponentB,...
        dxyz, ...
        rAB,...
        overlapSASB);
    gauMinsAB = gaussianExponentA-gaussianExponentB;
    value = 0.5*gauMinsAB...
        +3.0*(gaussianExponentB*gaussianExponentB)*gaussianExponentA...
        *(dxyz(axis)*dxyz(axis))/(gauPlusAB*gauPlusAB)...
        +gaussianExponentB*(gaussianExponentA*gaussianExponentA)...
        *(2.0*(dxyz(3)*dxyz(3)) - (dxyz(1)*dxyz(1)) - (dxyz(2)*dxyz(2)))/(2.0*gauPlusAB)...
        +(gaussianExponentB*gaussianExponentB*gaussianExponentB)*(gaussianExponentA*gaussianExponentA)*(dxyz(axis)*dxyz(axis))...
        *(2.0*(dxyz(3)*dxyz(3)) - (dxyz(1)*dxyz(1)) - (dxyz(2)*dxyz(2)))/(gauPlusAB*gauPlusAB);
    value = value .* (-8.0*gauMultAB*dxyz(anotherAxis)/(sqrt(3.0)*(gauPlusAB*gauPlusAB*gauPlusAB)));
    value = value .* overlapSASB;
    value = value + xyzA(axis)*overlapAOs1;
elseif( (valenceOrbitalA == 7 && axis == 2 && valenceOrbitalB == 6) ||...
        (valenceOrbitalA == 7 && axis == 1 && valenceOrbitalB == 8) )
    overlapAOs1 = obj.GetGaussianOverlapAOs(atomTypeA,...
        valenceOrbitalA, ...
        gaussianExponentA, ...
        atomTypeB, ...
        valenceOrbitalB, ...
        gaussianExponentB,...
        dxyz, ...
        rAB,...
        overlapSASB);
    value = gaussianExponentB-0.5*gaussianExponentA...
        +gaussianExponentA*(gaussianExponentB*gaussianExponentB)...
        *(2.0*(dxyz(3)*dxyz(3)) - (dxyz(1)*dxyz(1)) - (dxyz(2)*dxyz(2)))/(2.0*gauPlusAB)...
        +(gaussianExponentA*gaussianExponentA*gaussianExponentA)...
        *(gaussianExponentB*gaussianExponentB*dxyz(axis)*dxyz(axis))...
        *(2.0*(dxyz(3)*dxyz(3)) - (dxyz(1)*dxyz(1)) - (dxyz(2)*dxyz(2)))...
        /(gauPlusAB*gauPlusAB);
    value = value .* 8.0*gauMultAB*dxyz(3)...
        /(sqrt(3.0)*(gauPlusAB*gauPlusAB*gauPlusAB));
    value = value .* overlapSASB;
    value = value + xyzB(axis)*overlapAOs1;
elseif( (valenceOrbitalA == 6 && axis == 2 && valenceOrbitalB == 7) ||...
        (valenceOrbitalA == 8 && axis == 1 && valenceOrbitalB == 7) )
    overlapAOs1 = obj.GetGaussianOverlapAOs(atomTypeA,...
        valenceOrbitalA, ...
        gaussianExponentA, ...
        atomTypeB, ...
        valenceOrbitalB, ...
        gaussianExponentB,...
        dxyz, ...
        rAB,...
        overlapSASB);
    value = gaussianExponentA-0.5*gaussianExponentB...
        +gaussianExponentB*(gaussianExponentA*gaussianExponentA)...
        *(2.0*(dxyz(3)*dxyz(3)) - (dxyz(1)*dxyz(1)) - (dxyz(2)*dxyz(2)))/(2.0*gauPlusAB)...
        +(gaussianExponentB*gaussianExponentB*gaussianExponentB)*(gaussianExponentA*gaussianExponentA*dxyz(axis)*dxyz(axis))...
        *(2.0*(dxyz(3)*dxyz(3)) - (dxyz(1)*dxyz(1)) - (dxyz(2)*dxyz(2)))...
        /(gauPlusAB*gauPlusAB);
    value = value .* (-8.0*gauMultAB*dxyz(3)...
        /(sqrt(3.0)*(gauPlusAB*gauPlusAB*gauPlusAB)));
    value = value .* overlapSASB;
    value = value + xyzA(axis)*overlapAOs1;
elseif( (valenceOrbitalA == 7 && axis == 3 && valenceOrbitalB == 6) ||...
        (valenceOrbitalA == 7 && axis == 3 && valenceOrbitalB == 8) )
    if(valenceOrbitalB == 6)
        anotherAxis = 2;
    elseif(valenceOrbitalB == 8)
        anotherAxis = 1;
    end
    overlapAOs1 = obj.GetGaussianOverlapAOs(atomTypeA,...
        valenceOrbitalA, ...
        gaussianExponentA, ...
        atomTypeB, ...
        valenceOrbitalB, ...
        gaussianExponentB,...
        dxyz, ...
        rAB,...
        overlapSASB);
    value = gaussianExponentA-0.5*gaussianExponentB...
        -3.0*(gaussianExponentA*gaussianExponentA)*gaussianExponentB...
        *dxyz(axis)*dxyz(axis)/(gauPlusAB*gauPlusAB)...
        +gaussianExponentA*(gaussianExponentB*gaussianExponentB)...
        *(2.0*(dxyz(3)*dxyz(3)) - (dxyz(1)*dxyz(1)) - (dxyz(2)*dxyz(2)))/(2.0*gauPlusAB)...
        +(gaussianExponentA*gaussianExponentA*gaussianExponentA)...
        *(gaussianExponentB*gaussianExponentB*dxyz(axis)*dxyz(axis))...
        *(2.0*(dxyz(3)*dxyz(3)) - (dxyz(1)*dxyz(1)) - (dxyz(2)*dxyz(2)))...
        /(gauPlusAB*gauPlusAB);
    value = value .* 8.0*gauMultAB*dxyz(anotherAxis)...
        /(sqrt(3.0)*(gauPlusAB*gauPlusAB*gauPlusAB));
    value = value .* overlapSASB;
    value = value + xyzB(axis)*overlapAOs1;
elseif( (valenceOrbitalA == 6 && axis == 3 && valenceOrbitalB == 7) ||...
        (valenceOrbitalA == 8 && axis == 3 && valenceOrbitalB == 7) )
    if(valenceOrbitalA == 6)
        anotherAxis = 2;
    elseif(valenceOrbitalA == 8)
        anotherAxis = 1;
    end
    overlapAOs1 = obj.GetGaussianOverlapAOs(atomTypeA,...
        valenceOrbitalA, ...
        gaussianExponentA, ...
        atomTypeB, ...
        valenceOrbitalB, ...
        gaussianExponentB,...
        dxyz, ...
        rAB,...
        overlapSASB);
    value = gaussianExponentB-0.5*gaussianExponentA...
        -3.0*(gaussianExponentB*gaussianExponentB)*gaussianExponentA*dxyz(axis)*dxyz(axis)/(gauPlusAB*gauPlusAB)...
        +gaussianExponentB*(gaussianExponentA*gaussianExponentA)...
        *(2.0*(dxyz(3)*dxyz(3)) - (dxyz(1)*dxyz(1)) - (dxyz(2)*dxyz(2)))/(2.0*gauPlusAB)...
        +(gaussianExponentB*gaussianExponentB*gaussianExponentB)...
        *(gaussianExponentA*gaussianExponentA*dxyz(axis)*dxyz(axis))...
        *(2.0*(dxyz(3)*dxyz(3)) - (dxyz(1)*dxyz(1)) - (dxyz(2)*dxyz(2)))...
        /(gauPlusAB*gauPlusAB);
    value = value .* (-8.0*gauMultAB*dxyz(anotherAxis)...
        /(sqrt(3.0)*(gauPlusAB*gauPlusAB*gauPlusAB)));
    value = value .* overlapSASB;
    value = value + xyzA(axis)*overlapAOs1;
elseif(valenceOrbitalA == 7 && axis == 1 && valenceOrbitalB == 9)
    axisAverage = (gaussianExponentA*xyzA(axis)+gaussianExponentB*xyzB(axis))/gauPlusAB;
    overlapAOs1 = obj.GetGaussianOverlapAOs(atomTypeA,...
        valenceOrbitalA, ...
        gaussianExponentA, ...
        atomTypeB, ...
        valenceOrbitalB, ...
        gaussianExponentB,...
        dxyz, ...
        rAB,...
        overlapSASB);
    value = gaussianExponentB - gaussianExponentA...
        +gaussianExponentA*(gaussianExponentB*gaussianExponentB)...
        *(2.0*(dxyz(3)*dxyz(3)) - (dxyz(1)*dxyz(1)) - (dxyz(2)*dxyz(2)))/gauPlusAB...
        +(gaussianExponentA*gaussianExponentA)*gaussianExponentB...
        *((dxyz(1)*dxyz(1)) - (dxyz(2)*dxyz(2)))/gauPlusAB;
    value = value .* 4.0*gauMultAB*dxyz(1)/(gauPlusAB*gauPlusAB*gauPlusAB*sqrt(3.0));
    value = value .* overlapSASB;
    value = value + axisAverage*overlapAOs1;
elseif(valenceOrbitalA == 9 && axis == 1 && valenceOrbitalB == 7)
    axisAverage = (gaussianExponentA*xyzA(axis)+gaussianExponentB*xyzB(axis))/gauPlusAB;
    overlapAOs1 = obj.GetGaussianOverlapAOs(atomTypeA,...
        valenceOrbitalA, ...
        gaussianExponentA, ...
        atomTypeB, ...
        valenceOrbitalB, ...
        gaussianExponentB,...
        dxyz, ...
        rAB,...
        overlapSASB);
    value = gaussianExponentA - gaussianExponentB...
        +gaussianExponentB*(gaussianExponentA*gaussianExponentA)...
        *(2.0*(dxyz(3)*dxyz(3)) - (dxyz(1)*dxyz(1)) - (dxyz(2)*dxyz(2)))/gauPlusAB...
        +(gaussianExponentB*gaussianExponentB)*gaussianExponentA...
        *((dxyz(1)*dxyz(1)) - (dxyz(2)*dxyz(2)))/gauPlusAB;
    value = value .* (-4.0*gauMultAB*dxyz(1)/(gauPlusAB*gauPlusAB*gauPlusAB*sqrt(3.0)));
    value = value .* overlapSASB;
    value = value + axisAverage*overlapAOs1;
elseif(valenceOrbitalA == 7 && axis == 2 && valenceOrbitalB == 9)
    axisAverage = (gaussianExponentA*xyzA(axis)+gaussianExponentB*xyzB(axis))/gauPlusAB;
    overlapAOs1 = obj.GetGaussianOverlapAOs(atomTypeA,...
        valenceOrbitalA, ...
        gaussianExponentA, ...
        atomTypeB, ...
        valenceOrbitalB, ...
        gaussianExponentB,...
        dxyz, ...
        rAB,...
        overlapSASB);
    value = gaussianExponentB - gaussianExponentA...
        +gaussianExponentA*(gaussianExponentB*gaussianExponentB)...
        *(2.0*(dxyz(3)*dxyz(3)) - (dxyz(1)*dxyz(1)) - (dxyz(2)*dxyz(2)))/gauPlusAB...
        +(gaussianExponentA*gaussianExponentA)*gaussianExponentB...
        *((dxyz(2)*dxyz(2)) - (dxyz(1)*dxyz(1)))/gauPlusAB;
    value = value .* (-4.0*gauMultAB*dxyz(2)/(gauPlusAB*gauPlusAB*gauPlusAB*sqrt(3.0)));
    value = value .* overlapSASB;
    value = value + axisAverage*overlapAOs1;
elseif(valenceOrbitalA == 9 && axis == 2 && valenceOrbitalB == 7)
    axisAverage = (gaussianExponentA*xyzA(axis)+gaussianExponentB*xyzB(axis))/gauPlusAB;
    overlapAOs1 = obj.GetGaussianOverlapAOs(atomTypeA,...
        valenceOrbitalA, ...
        gaussianExponentA, ...
        atomTypeB, ...
        valenceOrbitalB, ...
        gaussianExponentB,...
        dxyz, ...
        rAB,...
        overlapSASB);
    value = gaussianExponentA - gaussianExponentB...
        +gaussianExponentB*(gaussianExponentA*gaussianExponentA)...
        *(2.0*(dxyz(3)*dxyz(3)) - (dxyz(1)*dxyz(1)) - (dxyz(2)*dxyz(2)))/gauPlusAB...
        +(gaussianExponentB*gaussianExponentB)*gaussianExponentA...
        *((dxyz(2)*dxyz(2)) - (dxyz(1)*dxyz(1)))/gauPlusAB;
    value = value .* 4.0*gauMultAB*dxyz(2)/(gauPlusAB*gauPlusAB*gauPlusAB*sqrt(3.0));
    value = value .* overlapSASB;
    value = value + axisAverage*overlapAOs1;
elseif(valenceOrbitalA == 7 && axis == 3 && valenceOrbitalB == 9)
    axisAverage = (gaussianExponentA*xyzA(axis)+gaussianExponentB*xyzB(axis))/gauPlusAB;
    overlapAOs1 = obj.GetGaussianOverlapAOs(atomTypeA,...
        valenceOrbitalA, ...
        gaussianExponentA, ...
        atomTypeB, ...
        valenceOrbitalB, ...
        gaussianExponentB,...
        dxyz, ...
        rAB,...
        overlapSASB);
    value = (dxyz(1)*dxyz(1)) - (dxyz(2)*dxyz(2));
    value = value .* (-8.0*(gaussianExponentA*gaussianExponentA*gaussianExponentA)*(gaussianExponentB*gaussianExponentB)*dxyz(3));
    value = value ./ (sqrt(3.0)*gauPlusAB*gauPlusAB*gauPlusAB*gauPlusAB);
    value = value .* overlapSASB;
    value = value + axisAverage*overlapAOs1;
elseif(valenceOrbitalA == 9 && axis == 3 && valenceOrbitalB == 7)
    axisAverage = (gaussianExponentA*xyzA(axis)+gaussianExponentB*xyzB(axis))/gauPlusAB;
    overlapAOs1 = obj.GetGaussianOverlapAOs(atomTypeA,...
        valenceOrbitalA, ...
        gaussianExponentA, ...
        atomTypeB, ...
        valenceOrbitalB, ...
        gaussianExponentB,...
        dxyz, ...
        rAB,...
        overlapSASB);
    value = (dxyz(1)*dxyz(1)) - (dxyz(2)*dxyz(2));
    value = value .* 8.0*(gaussianExponentA*gaussianExponentA)*(gaussianExponentB*gaussianExponentB*gaussianExponentB)*dxyz(3);
    value = value ./ (sqrt(3.0)*gauPlusAB*gauPlusAB*gauPlusAB*gauPlusAB);
    value = value .* overlapSASB;
    value = value + axisAverage*overlapAOs1;
else
    throw(MException('Cndo2:GetGaussianCartesianMatrix', 'Orbital type wrong.'));
end

end